### PR TITLE
add spanish translation

### PR DESCRIPTION
**Pull request by beriain**

### CODE REVIEW

**Comment by F4uzan** [comment]
Seems all okay to me. Can you add the entry to the credits file? I'll do it in a future commit if you can't.

**Comment by beriain** [comment]
Done

**Comment by F4uzan** [comment]
Thanks! I'm currently in vacation, hence why I can't quite do the changes easily. Will be merging this now.

**Comment by beriain** [comment]
Don't worry, there's no need to hurry. Have fun and enjoy your vacation 😃

**Pull request merged**
